export const TAUTH = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAILURE: "LOGIN_REQUEST_FAILURE",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",
};
