export const userData = [
  {
    created_time: new Date(2006, 7, 24),
    user_id: 1,
    name: "rahul",
    password: "hashedPassword",
    gender: "male",
    email: "rahul@gmail.com",
    mobile: "1234567980",
    profile_image_src: "location/to/file",
    categories: {
      income: [
        "wages",
        "gifts_received",
        "refunds",
        "loan_returns",
        "cashbacks",
        "business",
        "loans_taken",
        "interest",
        "dividends",
        "investments",
        "others",
      ],
      expense: [
        {
          category: "home/essentials",
          sub_categories: [
            "groceries",
            "rent",
            "electricity",
            "gas",
            "water",
            "maintenance",
            "phone",
            "internet",
            "tv",
            "appliances",
            "garden",
            "milk",
            "food",
            "ott",
            "newspaper",
            "others",
          ],
        },
        {
          category: "taxes/loans",
          sub_categories: [
            "vehicle_loan",
            "home_loan",
            "gold_loan",
            "taxes",
            "bank_charges",
            "others",
          ],
        },
        {
          category: "life_style",
          sub_categories: [
            "clothing",
            "cleaning",
            "education",
            "saloon",
            "food",
            "personal_supplies",
            "gadgets",
            "others",
          ],
        },
        {
          category: "entertainment",
          sub_categories: [
            "movies",
            "books",
            "games",
            "vacation",
            "sports",
            "party",
            "others",
          ],
        },
        {
          category: "investments",
          sub_categories: [
            "stocks",
            "mutual_funds",
            "crypto_currency",
            "pension_fund(PF)",
            "business",
            "others",
          ],
        },
        {
          category: "health",
          sub_categories: [
            "medicines",
            "OPD",
            "health_insurance",
            "lab_tests",
            "others",
          ],
        },
        {
          category: "travel",
          sub_categories: ["fuel", "repairs", "maintenance", "fare", "others"],
        },
        {
          category: "donations",
          sub_categories: ["gifts", "charity", "donations", "others"],
        },
      ],
    },
    date_of_birth: new Date(31, 3, 1996),
    country: "India",
    last_updated_time: new Date(31, 3, 2022),
  },
  {
    created_time: new Date(24, 9, 2010),
    user_id: 2,
    name: "anasuya",
    password: "hashedPassword",
    gender: "female",
    email: "anasuya007@gmail.com",
    mobile: "5689741236",
    profile_image_src: "location/to/file",
    categories: {
      income: [
        "wages",
        "gifts_received",
        "loan_returns",
        "cashbacks",
        "business",
        "loans_taken",
        "interest",
        "dividends",
        "investments",
        "others",
      ],
      expense: [
        {
          category: "home/essentials",
          sub_categories: [
            "groceries",
            "rent",
            "electricity",
            "gas",
            "water",
            "maintenance",
            "phone",
            "internet",
            "tv",
            "garden",
            "milk",
            "food",
            "ott",
            "newspaper",
            "others",
          ],
        },
        {
          category: "taxes/loans",
          sub_categories: [
            "vehicle_loan",
            "home_loan",
            "gold_loan",
            "taxes",
            "bank_charges",
            "others",
          ],
        },
        {
          category: "life_style",
          sub_categories: [
            "clothing",
            "cleaning",
            "education",
            "saloon",
            "food",
            "personal_supplies",
            "gadgets",
            "others",
          ],
        },
        {
          category: "entertainment",
          sub_categories: [
            "movies",
            "books",
            "games",
            "vacation",
            "sports",
            "others",
          ],
        },
        {
          category: "investments",
          sub_categories: [
            "stocks",
            "mutual_funds",
            "crypto_currency",
            "pension_fund(PF)",
            "business",
            "others",
          ],
        },
        {
          category: "health",
          sub_categories: [
            "medicines",
            "OPD",
            "health_insurance",
            "lab_tests",
            "others",
          ],
        },
        {
          category: "travel",
          sub_categories: ["fuel", "repairs", "maintenance", "fare", "others"],
        },
        {
          category: "donations",
          sub_categories: ["gifts", "charity", "donations", "others"],
        },
      ],
    },
    date_of_birth: new Date(13, 4, 1998),
    country: "Canada",
    last_updated_time: new Date(31, 3, 2022),
  },
];

export const accountsData = [
  {
    created_time: new Date(24, 7, 2006),
    account_id: 101,
    user_id: 1,
    account_name: "cash",
    balance: 12500,
    last_updated_time: new Date(31, 3, 2022),
  },
  {
    created_time: new Date(19, 4, 2005),
    account_id: 102,
    user_id: 2,
    account_name: "cash",
    balance: 50000,
    last_updated_time: new Date(31, 3, 2022),
  },
  {
    created_time: new Date(15, 3, 2008),
    account_id: 103,
    user_id: 1,
    account_name: "hdfc",
    balance: 30,
    last_updated_time: new Date(31, 3, 2022),
  },
  {
    created_time: new Date(24, 9, 2010),
    account_id: 104,
    user_id: 2,
    account_name: "sbi",
    balance: 630,
    last_updated_time: new Date(31, 3, 2022),
  },
];

export const transactionsData = [
  {
    created_time: new Date(4, 2, 2022),
    transaction_id: 1001,
    user_id: 1,
    type: "income",
    date_of_transaction: new Date(4, 2, 2022),
    amount: 500,
    category: "wages",
    sub_category: "NA",
    from_account: "NA",
    to_account: 103,
    notes: "received salary",
    last_updated_time: new Date(5, 2, 2022),
  },
  {
    created_time: new Date(12, 2, 2022),
    transaction_id: 1002,
    user_id: 1,
    type: "expense",
    date_of_transaction: new Date(12, 2, 2022),
    amount: 3500,
    category: "taxes",
    sub_category: "vehicle",
    from_account: 101,
    to_account: "NA",
    notes: "Car EMI",
    last_updated_time: new Date(12, 2, 2022),
  },
  {
    created_time: new Date(25, 2, 2022),
    transaction_id: 1003,
    user_id: 1,
    type: "self",
    date_of_transaction: new Date(25, 2, 2022),
    amount: 3500,
    category: "NA",
    sub_category: "NA",
    from_account: 101,
    to_account: 103,
    notes: "Internal Transfer",
    last_updated_time: new Date(25, 2, 2022),
  },
  {
    created_time: new Date(4, 2, 2022),
    transaction_id: 1004,
    user_id: 2,
    type: "income",
    date_of_transaction: new Date(4, 2, 2022),
    amount: 500,
    category: "wages",
    sub_category: "NA",
    from_account: "NA",
    to_account: 102,
    notes: "received salary",
    last_updated_time: new Date(5, 2, 2022),
  },
  {
    created_time: new Date(12, 2, 2022),
    transaction_id: 1005,
    user_id: 2,
    type: "expense",
    date_of_transaction: new Date(12, 2, 2022),
    amount: 3500,
    category: "taxes",
    sub_category: "vehicle",
    from_account: 104,
    to_account: "NA",
    notes: "Car EMI",
    last_updated_time: new Date(12, 2, 2022),
  },
  {
    created_time: new Date(25, 2, 2022),
    transaction_id: 1006,
    user_id: 2,
    type: "self",
    date_of_transaction: new Date(25, 2, 2022),
    amount: 3500,
    category: "NA",
    sub_category: "NA",
    from_account: 102,
    to_account: 104,
    notes: "Internal Transfer",
    last_updated_time: new Date(25, 2, 2022),
  },
];

export const loggedInUser = userData[1];

export const loggedInUserAccounts = accountsData.filter(
  (data) => data.user_id === loggedInUser.user_id
);
